#!/usr/bin/env node

let Web3 = require('web3');
let contract = require("truffle-contract");

let provider = new Web3.providers.HttpProvider("http://localhost:8545");
let web3 = new Web3(provider);

let coinAbi = require('./build/contracts/PonziTokenV3.json');
var POWH = contract(coinAbi);
POWH.setProvider(provider);

if(process.argv[2] == 1){
	POWH.deployed().then((instance) => {

	var you_b1 = web3.fromWei(web3.eth.getBalance(web3.eth.accounts[0]))
	var you_b2 = web3.fromWei(web3.eth.getBalance(web3.eth.accounts[1]))
	var coin_b = web3.fromWei(web3.eth.getBalance(instance.address))

	if(you_b1 >= 1000 || you_b2 >= 1000 ){
		console.log("Congratulations: You have solved Challenge !!!!")
		console.log('PoWH contract: ' + coin_b + ' ETH');
		console.log('YOU: ' + web3.fromWei(web3.eth.getBalance(web3.eth.accounts[0])) + ' ETH');
		console.log('YOU: ' + web3.fromWei(web3.eth.getBalance(web3.eth.accounts[1])) + ' ETH');
	} else {
		console.log("Try harder, time is ticking!")
	}

	})
	.catch(function(error) {
		console.log("Something went wrong.")
	});
}