#!/bin/bash
if [ "$1" == "" ]; then
    echo "Please select level 1 or 2"
    exit
else
	trap 'kill $(jobs -p)' EXIT
	rm -rf build
    if [ "$1" == "1" ]; then
		rm ./contracts/WalletLibrary.sol
		rm ./contracts/Wallet.sol
		cp ./library/WalletLibrary.sol ./contracts/WalletLibrary.sol
		cp ./library/Wallet.sol ./contracts/Wallet.sol	
	elif [ "$1" == "2" ]; then
		rm ./contracts/WalletLibrary.sol
		rm ./contracts/Wallet.sol
		cp ./library/WalletLibraryPatched.sol ./contracts/WalletLibrary.sol
		cp ./library/WalletPatched.sol ./contracts/Wallet.sol	
    fi	
fi


KEY1="D2823AE08A737570063BCC8A6D396D6A8A5C2B2A4CD4A5BA79C9AA349AF7205F"
KEY2="2711FE682D8E627393F240686FC49E3AD0CD822A736CAE7FFEECD33924D99BF0"

printf "Running test network...\n"
npx ganache-cli --account '0x601aaaf5f9ac507ffd34eb3b10bb1bf7b382bf312f460572ba207e4e2b221787, 20000000000000000000' --account "0x$KEY1, 50000100000000000000000" --account "0x$KEY2, 50000100000000000000000" -l 50000000 >/dev/null  & 


printf "Deploying the contracts ..\n"
npx truffle migrate --network challenge
printf "\n=========================================================================================\n\n"

printf "Happy Hacking\n\n"

for i in `seq 1 1337`; do
    sleep 1337
    echo -n "."
done